### ISSUE TITLE
Shell greeter - printout errors

### ISSUE THREAD

**Issue by Janiaje** [andresgongora/synth-shell-greeter#28]
**Describe the bug**
Before the logo there are some errors displayed:so
![Screenshot from 2020-11-24 00-08-40](https://user-images.githubusercontent.com/25385437/100025543-4ef15200-2de9-11eb-8130-9073fda1624e.png)

**To Reproduce**
1. Clear install on Ubuntu 20 following the stepts in the README.md
2. Startup a terminal

**Expected behavior**
No errors displayed.

**Comment by andresgongora** [comment]
This issue might be related to #24 . Can you check whether you have `bc` installed?

sudo apt-get install bc

**Comment by Janiaje** [comment]
It is already installed:

![image](https://user-images.githubusercontent.com/25385437/100382666-1ab1a780-301c-11eb-98c0-d3498e28d925.png)

**Comment by andresgongora** [comment]
Ok, then it's probably related to your `locale`. Do you write decimals with `,` or `.` (e.g., `13.2` vs `13,2`)?
I've pushed a new fix that should solve this. Just update your repository from master and try again. Please let me know if it worked ;)

**Comment by andresgongora** [comment]
@Janiaje Did it work? :)

**Comment by Janiaje** [comment]
Sry for the delay.

It did not work though I am not sure I reinstalled it properly:
 * Reinstall: ![image](https://user-images.githubusercontent.com/25385437/100676810-e87cae80-3369-11eb-80da-992d5c3af2f4.png)
 * It only added a duplication to the `.bashrc` file. (Line 166-170 is the newly added part) ![image](https://user-images.githubusercontent.com/25385437/100676924-2da0e080-336a-11eb-9077-ae9ff84dca14.png)

And now it prints out the greeter twice on terminal startup (the error message is there before each greeter).

**Comment by Janiaje** [comment]
My `locale` is the following:
![image](https://user-images.githubusercontent.com/25385437/100677366-28906100-336b-11eb-864c-c16bb788fd85.png)

It uses `,` to write decimals:
![image](https://user-images.githubusercontent.com/25385437/100677340-1adadb80-336b-11eb-8e29-c85b2f95fdbd.png)

**Comment by Janiaje** [comment]
I ran the `~/.config/synth-shell/uninstall.sh` and reinstalled from the bginning and I still get the error messages

**Comment by andresgongora** [comment]
Sorry it took so long. The issue is that I only fixed the `bc` problem in one file, when there where several files using it. I've fixed the whole issue by calling the script with LANG=C for everything (see `/synth-shell-greeter/synth-shell-greeter.sh` line 248).

This should solve the problem once and for all. Let's give it a try :)

**Comment by andresgongora** [comment]
> I ran the `~/.config/synth-shell/uninstall.sh` and reinstalled from the bginning and I still get the error messages

The uninstall script is quite broken... I fear. It does not remove all files, really. But reinstalling should fix the issue

**Comment by andresgongora** [comment]
Quick fix. I'm on my way to work: go to ~/.bashrc and edit it with a text
editor. At the bottom you should find two blocks that call
synth-shell-greeter. Remove one of them and that should fix the duplication
problem.

Ok. The error is 100% related to . vs ,

I'll have a look at it later. Thanks for all your feedback on tracking this
issue!

**Comment by andresgongora** [comment]
@Janiaje I sent a message last Tuesday but it's not listed here. Odd.
I think I've fixed it now. Please upadte your master branch and just follow the usual install process. Uninstalling is not required.

If you get a double prompt:
```
nano ~/.bashrc
```
And delete everyline that says synth-shell. Then reinstall and open a new terminal :)

**Comment by andresgongora** [comment]
I've created a test setup and I'm able to reproduce the error but I'm still not sure of the cause. Working on it...

**Comment by Janiaje** [comment]
Thank you for working on it! :)

**Comment by andresgongora** [comment]
The problem is 99.99% related to the locale it is run with. I've edited the script so that it runs with `LANG=C`.

Just in case, @Janiaje try the following:
```
## Should work fine:
LANG=C source .config/synth-shell/synth-shell-prompt.sh

## If it fails, it's with this. Maybe it no longer fails:
LANG=hu_HU.utf8 source .config/synth-shell/synth-shell-prompt.sh
```

To install the latest version of synthshell (I've edited the setup script, so you might want to create a clean install):

1. Edit `~/.bashrc` and remove the lines reffering to synth-shell, usually at the bottom of the file. 
```
nano ~/.bashrc
```

2. Remove the folder containing the script, should be in your home folder. Maybe you want to backup your config and logo first.
```
rm -r ~/.config/synth-shell/
```

3. Clean synth-shell setup:
```
git clone --recursive https://github.com/andresgongora/synth-shell.git
chmod +x synth-shell/setup.sh
synth-shell/setup.sh
```

**Comment by andresgongora** [comment]
P.S.: your bash prompt would look nicer if you install the font `hack-ttf` or `ttf-hack` and tell your terminal (I guess it's gnome-terminal??) to use that instead of the default ubuntu-mono font ;)
